name: 💡 Feature request
description: Suggest an idea to help improve this project
title: '[Feature]: '
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion!
  - type: checkboxes
    id: terms
    attributes:
      label: Please take a moment to familiarize yourself with this project scope and standards
      options:
        - label: I have read the [Documentation](https://github.com/stefanobartoletti/nuxt-social-share?tab=readme-ov-file) and I understand how to correctly use this module.
          required: true
        - label: I have read the [Contributing Guidelines](https://github.com/stefanobartoletti/nuxt-social-share/blob/main/.github/CONTRIBUTING.md).
          required: true
        - label: I agree to follow this project's [Code of Conduct](https://github.com/stefanobartoletti/nuxt-social-share?tab=coc-ov-file)
          required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Describe your idea
      description: Please provide a clear, concise and understandable description of your idea. Also include the possible use cases and alternatives you have considered.
    validations:
      required: true
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: After this idea has been discussed and approved, would you be willing to contribute to the implementation of this feature?
      options:
        - label: I am willing to contribute to the implementation of this feature.
