blank_issues_enabled: true
contact_links:
  - name: 📚 Documentation
    url: https://github.com/stefanobartoletti/nuxt-social-share/blob/main/README.md
    about: Check the documentation for usage of this moudule
  - name: 💬 Questions & Discussions
    url: https://github.com/stefanobartoletti/nuxt-social-share/discussions
    about: Use discussions if you have another issue, an idea for improvement or for asking questions.
